### ISSUE TITLE
iLike method with accent.

### ISSUE THREAD

**Issue by GabrielGoncalvesMendes** [feathersjs-ecosystem/feathers-sequelize#385] opened 2022-01-12 01:33 UTC
### Expected behavior
It should return all names even if passed without accent in the search. ex: joao, it should search all the users that contain these characters along with the names with accents ex: joão.

### Actual behavior
It is performing the search with the same names that contain the special character in the case of ã, when it should search for all types of Joao, even without passing the ã.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
"@feathersjs/feathers": "^4.5.11",
"@feathersjs/express": "^4.5.11",
"feathers-sequelize": "^6.2.0",
"feathers-hooks-common": "^5.0.5",

**NodeJS version**: 16.13.0

**Operating System**: Ubuntu 20.04

**Browser Version**: Google Chrome Version 97.0.4692.71

**React Native Version**:

**Module Loader**:

The Request URL is: http://localhost:3030/path?$select[]=name&$select[]=id&$select[]=pictureUrl&$select[]=position&name[$iLike]=%25joa%25&$limit=5

We Pass iLike in query params but do not receive correct data it only works Sensitive data.

**Comment by fratzinger** [comment] 2022-04-26 08:03
What happens, if you search for `%joao%`?

**Comment by DaddyWarbucks** [comment] 2024-06-19 20:12
Closing this because it is outdated. The problem is likely because the Query was not urlEncoded and likely had misuse of `%%`

**Closed by DaddyWarbucks** 2024-06-19 20:12 UTC
